sre-capabilities a-i instance pr-check
APPSRE-8161

Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>

diff --git a/data/services/sre-capabilities/cicd/jobs.yaml b/data/services/sre-capabilities/cicd/jobs.yaml
--- a/data/services/sre-capabilities/cicd/jobs.yaml
+++ b/data/services/sre-capabilities/cicd/jobs.yaml
@@ -31,3 +31,34 @@ config:
         instance_name: sre-capabilities-stage
         s3_bucket_secret_path: app-sre/integrations-output/terraform-resources/appsres03ue1/sre-capabilities-stage/sre-capabilities-s3
         slack_channel_notification: sd-sre-capabilities-stage
+    - 'gl-pr-check-app-interface-instance':
+        display_name: SRE Capabilities schema validator pr-check
+        concurrent_build: true
+        ci_toml_secret_path: app-interface-instances/sre-capabilities-stage/ci-toml
+        s3_bucket_secret_path: app-sre/integrations-output/terraform-resources/appsres03ue1/sre-capabilities-stage/sre-capabilities-s3
+        state_bucket_secret_path: app-sre/integrations-output/terraform-resources/appsres03ue1/sre-capabilities-stage/sre-capabilities-s3
+        qontract_server_auth_secret_path: app-interface-instances/sre-capabilities-stage/qontract-server-creds
+        # This is a temporary workaround to prevent changes to the hack directory from running MR checks
+        pr_check_script_path: |
+            #!/bin/bash
+            set -evuo pipefail
+            if ! git diff --quiet origin/master HEAD -- ./hack/; then
+              MERGE_REQUEST_QUERY=api/v4/projects/"$gitlabMergeRequestTargetProjectId"/merge_requests/"$gitlabMergeRequestIid"
+              echo "Checking permission for merge request: $MERGE_REQUEST_QUERY ..."
+              AUTHOR_ID=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$GITLAB_SERVER/$MERGE_REQUEST_QUERY" | jq '.author.id')
+              if [ "$AUTHOR_ID" == "null" ]; then
+                echo "Author not found!"
+                exit 2
+              fi
+              MEMBER_QUERY=api/v4/groups/app-sre/members/"$AUTHOR_ID"
+              echo "Checking if author is a member of app-sre $MEMBER_QUERY ..."
+              STATUS_CODE=$(curl -s -o /dev/null -w "%{{http_code}}" --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$GITLAB_SERVER/$MEMBER_QUERY")
+              if [ "$STATUS_CODE" == "200" ]; then
+                echo "Found authorized hack/ folder change, MR will run."
+              else
+                echo "Found unauthorized hack/ folder change, MR will not run."
+                exit 2
+              fi
+            fi
+            ./hack/pr_check.sh
+        job_type: ''
